name: Release

on:
  # When any release tag is pushed.
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+.[0-9]+.[0-9]+(.[0-9]+)?'

env:
  COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}

jobs:
  release-adapter:
    runs-on: macos-latest
    steps:
      # Check out the repo.
      - name: Checkout
        uses: actions/checkout@v3

      # Push the podspec.
      - name: Push Podspec
        run: pod trunk push --verbose

      # Create GitHub release.
      - name: Create Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: ''
          draft: false
          prerelease: false
