name: Smoke Test

on:
  # On pull requests to main
  pull_request:
    branches:
      - main
  # Manual trigger from the Github Actions tab
  workflow_dispatch:

jobs:
  validate-podspec:
    runs-on: macos-latest
    steps:
      # Check out the repo.
      - name: Checkout
        uses: actions/checkout@v3

      # Check that the adapter version in the podpsec and in the PartnerAdapter Swift implementation are the same.
      - name: Validate Adapter and Podspec Version Match
        id: adapter_version_match
        run: echo "result=$(ruby ./Scripts/validate_adapter_version.rb)" >> $GITHUB_OUTPUT
        shell: bash

      # Fail if versions don't match
      - name: Fail on Adapter Version Mismatch
        if: ${{ steps.adapter_version_match.outputs.result != 'true' }}
        run: exit 1
        shell: bash

      # Validate the podspec.
      - name: Validate Podspec
        run: pod lib lint --verbose
